name: xonumi
favicon: null
layout_spectrum: 0.50932
typography_spectrum: 0.012297538109123707
title: the other side....
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
